### PR TITLE
Moved `api` arg

### PR DESCRIPTION
**Pull request by cool-ant**
Moved `--api` / `-a` arg to first position to mirror function of same `psibase` arg.

### CODE REVIEW

**Comment by swatanabe** [comment]
Why? I don't consider the argument order in psibase to be particularly great.

**Comment by cool-ant** [comment]
This approach achieves 2 things
1) make the position of this arg the same between psibase and cargo-psibase, eliminating one more exception-to-the-rule we need to remember when we use our tools
2) it eliminates a small amount of code replication that will only get worse as we add other commands to cargo-psibase

**Comment by swatanabe** [comment]
> > Why? I don't consider the argument order in psibase to be particularly great.
> 
> Symmetry is nice though

If symmetry is the goal, I'd rather change `psibase`

**Comment by swatanabe** [comment]
`clap` has a `global` flag to allow options to appear in any position.

**Comment by swatanabe** [comment]
Also, the `api` flag is only meaningful for commands that interact with the chain. Another way to reduce the code duplication is to bundle them in a struct and use `flatten`.

**Comment by cool-ant** [comment]
Closing this PR in the interest of a clean PR to implement what we decided (applying these changes to psibase rather than to cargo-psibase

**Pull request closed without merging**
